### PR TITLE
Updates and Fixes to the Site as a whole

### LINKED ISSUE #34: Enhancement: remove spaces in letter tier to reflect the fact that space bar is not needed
image

### LINKED ISSUE #50: Defect: DOT IO shows out of memory error
It happens when I click "populate table" and scroll down several  times. Attached are screenshots of the the error message and the output at the end of the console.  

Out of memory

output

### LINKED ISSUE #100: Enhancement: Delete or Implement the hamburger menu
From discord message https://discord.com/channels/861730583092658206/1086356304680984636/1130405579043647630

The hamburger menu doesn't work for now. Should delete or implement it.

### LINKED ISSUE #104: Defect: Multiple undefined are printed
From discord message https://discord.com/channels/861730583092658206/1086356304680984636/1130426317196763206

"Undefined" is printed multiple times when the:
- refresh? button is pressed at the middle of the page
- followed by the button with two right arrows
- and Test is clicked at the bottom of the page

### LINKED ISSUE #121: Enhancement: speed up the reading of chords from the device
`getGet()` from `download.tsx` is adding chords read from device one by one to the site. This is extremely slow (O(N^2) speed).

Chords should be read all at one up front, then bulk copied to the UI to save time

### PR DESCRIPTION
**Pull request by COChara**
Fixes #34 
Fixes #100 
Fixes #121 
Fixes #104
Fixes #50

### CODE REVIEW

File: src/helpers/aggregation.ts [hunk 1]
```diff
@@ -47,34 +47,48 @@ export const getCumulativeOccurrence = (stats: ChordStatistics[]): string => {
...
+export const wpmMethodCalculatorForStoredChords = (
+  value: number[],
+  inputLength?: number,
+) => {
   const sum = value?.reduce((a, b) => a + b, 0);
   const avg = sum / value?.length || 0;
 
   const avgSpeedMilliseconds = avg * 10;
-  const millisecondsPerCharacter = avgSpeedMilliseconds / 5;
+  const millisecondsPerCharacter = avgSpeedMilliseconds / (inputLength + 1);
```
Comment (rccarlson) [inline src/helpers/aggregation.ts:71]: `input + 1`? Shouldn't it just be inputLength?
